version: '3.8'

services:
  windows-mcp:
    image: yuzhounie/decodingtrust-macos
    container_name: macos-server
    environment:
      VERSION: "14"
      PASS: "docker"
      USER: "docker"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "${WEB_MANAGEMENT_PORT:-8006}:8006"      # Web-based management interface
      - "5900:5900/tcp"
      - "5900:5900/udp"
      - "${MCP_SERVICE_PORT:-8005}:8005"      # mcp service port
    volumes:
      - ./macos:/storage
      - ./mcp-remote-macos-use:/shared
    restart: always
    stop_grace_period: 2m